version: 1
services:
  - type: web
    name: collab
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: daphne -b 0.0.0.0 -p 8000 suhitha.asgi:application
    healthCheckPath: /
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: suhitha.settings