# Generated by Django 5.1.6 on 2025-04-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varuni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
