# Generated by Django 5.1.6 on 2025-04-11 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varuni', '0005_document_alter_userstatus_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='varuni.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
