# Generated by Django 5.1.6 on 2025-04-11 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varuni', '0006_delete_document_userstatus_room_alter_room_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='content',
        ),
        migrations.CreateModel(
            name='RoomContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='varuni.room')),
            ],
        ),
    ]
