# Generated by Django 5.2 on 2025-04-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varuni', '0007_remove_room_content_roomcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
